### ISSUE TITLE
Save Unsaved bug, working inconsistently with already existing docs

### ISSUE THREAD

**Issue by jurra** [Hardocs/hardocs-vue-apollo-client#14]
There is a strange reactivity issue going on with the rendering of the Save File button.
## Correct behavior
- When a new project is loaded in the app
- Then the user edits a document
- Then if not saved the Save file button should appear.
- Whe saved the button should disappear
## Unwanted and current behavior
- When a new project is loaded the button doesnt disappear or appear in the loaded docs, in coherence with change of state (``saved:true` or `saved:false`).
- When a  new document is added works as expected.
- If the `persisted state` plugin is used in vuex.
- When Ctrl + R is pressed, then all documents behave properly.

**Comment by DNature** [comment]
Are you still facing this issue?

**Comment by jurra** [comment]
Not anymore it was a problem related to my ram and development environment 
Closing this one
