### ISSUE TITLE
Refactoring of services from graphQL to pure and straight node processes

### ISSUE THREAD

**Issue by jurra** [Hardocs/hardocs-vue-apollo-client#16]
## Feature
We dont need a graphQL server to so basic file system management, this can be done directly with node, and served the functions respecting the same conventions we used in the services folder.

**Comment by jurra** [comment]
Hi @DNature we tried merging things together but the library is still not passing your tests.

**Comment by DNature** [comment]
Works perfectly now :)

**Comment by jurra** [comment]
This feature is not working properly yet.
I find different bugs when creating new files, deleting files and also when creating new projects.
It seems like these are all asyncronous related issues.

**Comment by DNature** [comment]
To easily/better test out all I've done separately with node and if you get an error then let me Know..

I think you're missing something somewhere

**Comment by DNature** [comment]
@jurra  I hope you're not facing any issues with the harrdocs-fs module after upgrading your PC's ram?
