### ISSUE TITLE
Import and integrate refactoring of fs node processes

### ISSUE THREAD

**Issue by jurra** [Hardocs/hardocs-vue-apollo-client#17]

**Comment by DNature** [comment]
All Done -- Right?

**Comment by jurra** [comment]
I found out that when I create a new project,
It takes a lot of time, even 5 minutes to create the docs folder inside the project.
The first thing that happend is that the docs folder didnt appear, then after sometime it appears.
So apparently is taking a lot of time to this fyle system operation in windows

**Comment by DNature** [comment]
Hi Jose. Everything works fine on my PC and I think there are a lot of processes running in the background of your computer that is slowing things down

**Comment by jurra** [comment]
This is done, and the bug was not related to this feature but something else
