### ISSUE TITLE
Fix css for links in the editor, provide clear styles like blue and underlined..

### ISSUE THREAD

**Issue by jurra** [Hardocs/hardocs-vue-apollo-client#31]
Currently links are not styled. Neither bullet points, can we configure this in the Ckeditor build?
Proper formatting of elements including links.

**Comment by DNature** [comment]
We now have the links, bullet points, tables and number list styles in place :) 
![Peek 2020-11-16 09-08](https://user-images.githubusercontent.com/49137104/99528104-1216fc80-299e-11eb-84fe-c826b782807a.gif)
